language: go
sudo: required

go:
  - 1.7

install:
  - make deps

script:
  - make stat

after_success:
  # grab pub/pri keys
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  # upload binary to binder
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/go_ip_updater*` --form path=go_ip_updater/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/go_ip_updater*` -form filename=go_ip_updater-latest-linux-amd64 --form path=go_ip_updater/ https://cryo.unixvoid.com/upload
